version: '3.8'

networks:
  kong-net:
    driver: bridge

services:
  kong-database:
    image: postgres:9.6
    restart: unless-stopped
    hostname: kong-database
    container_name: kong-database
    networks:
      - kong-net
    volumes:
      - ../.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong/kong-gateway:3.5.0.2
    restart: on-failure
    hostname: kong-migration
    container_name: kong-migration
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    command: kong migrations bootstrap

  kong:
    image: kong/kong-gateway:3.5.0.2
    restart: unless-stopped
    hostname: kong
    container_name: kong
    depends_on:
      - kong-migration
    networks:
      - kong-net
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
      - '8002:8002'
      - '8445:8445'
      - '8003:8003'
      - '8004:8004'
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002'
