version: '3.8'

services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: -Xmx6G # set Java options here
      SERVER_PORT: 2333 # set lavalink server port
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./lavalink/plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    deploy:
      replicas: 3

  lb:
    image: nginx
    volumes:
      - ./lavalink/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '2333:2333'
