version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ../.data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: helix_ai
      MYSQL_USER: helix_ai
      MYSQL_PASSWORD: zdqJ5zYmDEn1L07iAbBx
      MYSQL_ROOT_PASSWORD: hkjsdhflkjdsghcxbnkzxhlknblchihgjm
