version: '3'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'
    environment:
      # Save after 1hr if 1 write, after 5min if 100 writes, after 60 sec if 10000 writes
      REDIS_ARGS: --save 3600 1 300 100 60 10000
    volumes:
      - ../data/redis:/data
