name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use volta to set node/npm/yarn versions
        uses: volta-cli/action@v4
        with:
          package-json-path: '${{ github.workspace }}/package.json'

      - name: Use the package manager cache if available
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Nx test with code coverage
        run: npx nx test --code-coverage

      - name: Store code coverage report
        run: |
          COVERAGE_DIR="${{ github.workspace }}/coverage"
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          REPORT_DIR="${COVERAGE_DIR}/${TIMESTAMP}"

          mkdir -p "${REPORT_DIR}"
          cp -r coverage/lcov-report "${REPORT_DIR}"

      - name: Cleanup old code coverage reports
        run: |
          COVERAGE_DIR="${{ github.workspace }}/coverage"
          find "${COVERAGE_DIR}" -mindepth 1 -maxdepth 1 -type d -not -name "$(ls -t "${COVERAGE_DIR}" | head -n 1)" -exec rm -r {} +
