name: Open Pull Request on Git-Flow Branch

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'
      - 'release/*'
      - 'support/*'
      - 'develop'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Extract branch name
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Branch Name: $branch_name"

      - name: Install gh CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Create Pull Request
        run: |
          gh pr create --base develop --head "${branch_name}" --title "Merge ${branch_name} into develop" --body "This PR was automatically created by a GitHub Action."
