name: Open Pull Request on Git-Flow Branch

on:
  push:
    branches:
      - 'feature/*' # Adjust the branch pattern based on your git-flow configuration
      - 'bugfix/*' # Adjust the branch pattern based on your git-flow configuration
      - 'hotfix/*' # Adjust the branch pattern based on your git-flow configuration
      - 'release/*' # Adjust the branch pattern based on your git-flow configuration
      - 'support/*' # Adjust the branch pattern based on your git-flow configuration
      - 'develop' # Adjust the branch pattern based on your git-flow configuration

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Pull Request
        run: |
          branch_name=$(echo "${{ github.ref }}" | cut -d'/' -f 4)
          gh pr create --base develop --head "${branch_name}" --title "Merge ${branch_name} into develop"
